### ISSUE TITLE
Formatter: breaks other instances of grid ?

### ISSUE THREAD

**Issue by mchennupati** [grid-js/gridjs-react#137]
Hi, 
I have multiple grid instances in different components in my application (thanks for the amazing grid btw!). When I include a formatter to change the font color based on +/- in one of the grids. 

It also breaks the other grid instances. They all go into the state **Loading...**  and I don't see any errors on the console.

Commenting the formatter makes all the grids work. 

The grids all update based on a state but they all have different data from different sources.

I had an error saying **column id may be missing** when I changed the formatter from (cell)  to (cell, row) but that did not make any sense. Am I missing something obvious ?
Thanks a lot.

              {
                 name: "%",
                 formatter: (cell) => {
                   return _(
                     <b style={{ color: cell > 0 ? "green" : "red" }}>{cell}</b>
                   );
                 }
              }

**Comment by afshinm** [comment]
Sorry for the delay @mchennupati. Grid instances should work independently but I'm happy to look into that issue.

**Comment by mchennupati** [comment]
Hi Afshin, thanks for getting back. I figured another way to do it. You can close this and unless someone else brings up a similar issue later, it likely had to do with my code.
