### ISSUE TITLE
React component not rendered correctly at table header

### ISSUE THREAD

**Issue by naoyanickf** [grid-js/gridjs-react#210]
**Describe the bug**
I'm trying to render a react component at table header, not table cells.
It seems impossible

```
import { _ } from "gridjs-react";
const tableColumns = [
    {id: 'id', name: _(<button className={"py-2 px-4 border rounded-md text-white bg-blue-600"} onClick={() => alert('clicked!')}>Edit</button>)},
    {id: 'name', name: 'Name'},
]

<Grid
          columns={tableColumns}
          data=[[1,"hoge"], [2, "hoge"]
/>
 
```

this render only 

```
<button class="py-2 px-4 border rounded-md text-white bg-blue-600">Edit</button>
```

There isn't `onClick`

If possible, I want to put some react component at header .
My use-case is "Select All button"

**Comment by UserSina** [comment]
By rendering, do you mean that it won't show in the browser inspector? That's normal for React. I've tried the same example and the alert shows.

**Comment by naoyanickf** [comment]
@UserSina thanks! you're right!

thank you for trying!
