### ISSUE TITLE
Can't figure out how to use rowClick and cellClick events with this React adapter

### ISSUE THREAD

**Issue by RomLAURENT** [grid-js/gridjs-react#238]
**Is your feature request related to a problem? Please describe.**
I can't use the rowClick and cellClick events with this adapter

**Describe the solution you'd like**
The best will be to update the react adapter doc to add an example on using these events

**Describe alternatives you've considered**
I tried :

`<Grid` .... rowClick={(...args)=>console.log(args)} />`

and

`<Grid .... onRowClick={(...args)=>console.log(args)} />`

I'm currently exploring the source code to figure out the way to do this

**Additional context**
None.

**Comment by dcts** [comment]
I found a hacky way of doing this by using `useRef` and `useEffect`. Not sure if theres a better way but this works for me:

```jsx
import { Grid } from 'gridjs-react';
import { useRef, useEffect } from "react";

const MyComponent = () => {
  const gridRef = useRef();

  // add eventlistener onRowclick after component is first time rendered
  useEffect(() => {
    const gridjsInstance = gridRef.current.getInstance();
    gridjsInstance.on('rowClick', (...args) => console.log('row: ' + JSON.stringify(args), args));
  }, []);

  return (
    <div>
      <Grid
        ref={gridRef}
        data={[
          ['John', 'john@example.com', '(353) 01 222 3333'],
          ['Mark', 'mark@gmail.com', '(01) 22 888 4444'],
          ['Eoin', 'eo3n@yahoo.com', '(05) 10 878 5554'],
          ['Megan', 'nis900@gmail.com', '313 333 1923']
        ]}
        columns={['Name', 'Email', 'Phone Number']}
      />
    </div>
  );
};

export default MyComponent;
```

**Comment by ARedmanDodd** [comment]
Gonna bump this up again... 
Please can the docs give example on how the devs expect this behaviour to be handled?

**Comment by scottyadean** [comment]
I was able to do it by adding a onclick event by importing the render method " _ "
more info here:  https://gridjs.io/docs/examples/react-cells

Note: I renamed the imports because they conflicted with other vars in my project. 

```
import { Grid as GridTable, _ as GridFormat }  from 'gridjs-react';

//set columns
const cols = [ { id: 'property_address', 
    name: 'Address',
    formatter: (cell, row) => GridFormat(<span 
                    onClick={()=>console.log(`${row.cells[0].data} => ${row.cells[1].data}`)}> 
                    {cell}
                    </span>)
  }, 
  {id: 'address_state', name: 'State'}
  ];

//fake data
const data = [{property_address: "123 fake address fakecity CA 1000", address_state: "CA"}];

//render table
return (<GridTable data={data} columns={cols} />);

```
