### ISSUE TITLE
Use Link from react router in a cell

### ISSUE THREAD

**Issue by jimmybutton** [grid-js/gridjs-react#252]
**Describe the bug**
I am using react router and want to use a column formatter so that the user can click on the link within the cell and be guided to a detail page.

**To Reproduce**
Here is the column formatter i wanted to use:

```js
import { Link } from "react-router-dom";

const linkFormatter = (cell, row) =>
    _(
      <Link to={`/jobs/${row.cells[1].data}`} className="font-bold">
        {cell}
      </Link>
    );
```

I get the following error:
```Error: Invariant failed: You should not use <Link> outside a <Router>```

**Expected behavior**
Is there a way to make <Link /> work inside gridjs? Or maybe a workaround? I've tried using a regular `<a href="..." />` tag, which works, but I don't want to re-render the entire page. Many thanks!

**Comment by jimmybutton** [comment]
I've tried a few things but still wasn't able to make this work. Here is another approach I tried:

```javascript
const CellLink = ({ item }) => {
  let history = useHistory();
  function handleClick() {
    history.push(`/jobs/${item.jobId}`);
  }
  return (
    <button onClick={handleClick} className="font-bold">
      View
    </button>
  );
};

...

<Grid
  data={data.map((item) => ({
    ...item,
    button: _(<CellLink item={item} />),
  }))}
  columns={columns}
/>
```

If i use CellLink outside Grid it works, but if I use it in a cell, I get `TypeError: Cannot read property 'push' of undefined`.

Any advice would be greatly appreciated.

**Comment by arnigunnar** [comment]
Is there any way of reopening this, as I am having exactly the same issue.

**Comment by jimmybutton** [comment]
Hi @arnigunnar, just for you to know, I've switched to using React Table (https://react-table.tanstack.com/). It's a bit more work to set it up but it works great and allowes for more customization.

**Comment by a-r-i-e-l** [comment]
Send the history as a prop to CellLink

```
import { useHistory } from "react-router-dom";

const CellLink = ({ item, history }) => {
  function handleClick() {
    history.push(`/jobs/${item.jobId}`);
  }
  return (
    <button onClick={handleClick} className="font-bold">
      View
    </button>
  );
};

...

const WrapperComponent = () => {
  const history = useHistory();
  return (
    <Grid
      data={data.map((item) => ({
        ...item,
        button: _(<CellLink item={item} history={history} />),
      }))}
      columns={columns}
    />
  )
}
```

**Comment by dhoonbae** [comment]
[https://gridjs.io/docs/examples/cell-attributes](https://gridjs.io/docs/examples/cell-attributes)

const grid = new Grid({
  columns: [
      { 
        name: 'Name',
        attributes: (cell) => {
          // add these attributes to the td elements only
          if (cell) { 
            return {
              'data-cell-content': cell,
              'onclick': () => alert(cell),
              'style': 'cursor: pointer',
            };
          }
        }
      },
      'Email',
   ],
  data: Array(5).fill().map(x => [
    faker.name.findName(),
    faker.internet.email(),
  ])
});

[ react ]
import { useHistory } from 'react-router-dom';
const history = useHistory();
...
**onclick : () => history.push('/link')**
