### ISSUE TITLE
Error RN 17.0.1

### ISSUE THREAD

**Issue by smartdevdom** [grid-js/gridjs-react#256]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from gridjs-react@3.2.2
npm ERR! node_modules/gridjs-react
npm ERR!   gridjs-react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by amatzen** [comment]
Still an issue. Had to use --legacy-peer-deps for installing Grid.js to my React application.

**Comment by naterkane** [comment]
@amatzen i created [@naterkane/gridjs-react-17](https://npmjs.com/package/@naterkane/gridjs-react-17) in the interim to provide coverage until the PR to this repo is accepted. The only change is a patch version and a slightly different range for react as a peer dependency

**Comment by amatzen** [comment]
Thank you @naterkane ! I'll just mention your PR then to link the issue together with the PR #307
