### ISSUE TITLE
There should be an onSelect or onReady prop for the grid component.

### ISSUE THREAD

**Issue by maxxrdrgz** [grid-js/gridjs-react#277]
If there was a prop to handle the selection on ready event as mentioned here:
https://gridjs.io/docs/examples/selection-events

That'd make my life pretty easy, otherwise I don't know how to use the on ready event. 

Something like so:

foo = () = {
    //do stuff
}

<Grid
    data={data}
    columns={columns}
    search
    pagination={{
        limit: 5,
    }}
    **onSelect={this.foo}**
/>

**Comment by osmarpb97** [comment]
Any update?

**Comment by LightwithoutLisonlyight** [comment]
Same problem but with onClick / onRowClick

**Comment by LightwithoutLisonlyight** [comment]
@maxxrdrgz  I think this can help you
_Originally posted by @lamilsage in https://github.com/grid-js/gridjs/issues/502#issuecomment-829936133_

**Comment by maxxrdrgz** [comment]
@LightwithoutLisonlyight thanks. However, I ended up swapping out my library for this: https://www.npmjs.com/package/react-data-table-component
