### ISSUE TITLE
Please update to use React v18

### ISSUE THREAD

**Issue by ARedmanDodd** [grid-js/gridjs-react#401]
**Is your feature request related to a problem? Please describe.**
ReactDOM.render() is no longer supported by v18.* and any apps that do not use the new method of createRoot will be forced to run as though it is using React v17 -- gridjs-react also fails to install unless you use --force.

**Describe the solution you'd like**
Update to use React v18.*

**Comment by roeb** [comment]
Unfortunately, I still have the same problem. The following message still appears for me:

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/141244/214637368-2784f90f-5de1-4051-a2e4-61570a74448c.png">

Versions:
React: 18.2.0
Grid.js: 6.0.5
Grid.js-React: 6.0.1
