### ISSUE TITLE
Crash with l.createRoot is not a function when using formatter with server option

### ISSUE THREAD

**Issue by julienhocq** [grid-js/gridjs-react#407]
**Describe the bug**
I am trying to use formatter in React and are facing an issue even with the simple example from your documentation. The page crashes with this error:

 **l.createRoot is not a function**

My main goal is to use Link from react router and make the cell clickable. But I can't even make a simple example working.

**To Reproduce**
We are not 100% sure but we think the error is only happening when using with the server option but we didn't have time to create a minimal reproducible example.

Example of the props we passed to Grid component.
```
columns = {[{id: "id", name: "Actions", formatter: cell => _(<i>{cell}</i>) }]}
server={{
                  url: "/myapi",
                  then: data => data.rows,
                  total: data => data.count,
                }}
```

Any ideas?
Thanks!

**Expected behavior**
The page shouldn't crash and we should see our custom component.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Safari
 - Version: gridjs": "^5.1.0", "gridjs-react": "^5.1.0",

**Comment by julienhocq** [comment]
We finally tried an MRE (https://codesandbox.io/s/gridjs-mre-formatter-with-server-4qxrqy?file=/src/App.js ) and it works. 
The frustrating thing is that when we comment out in our code the line with the formatter or we changed to `formatter: cell => cell`  , it works perfectly.

**Comment by luciancic** [comment]
I see the error. This crash happens if you install react version 17.0.x. Here's a [reproduction of the error](https://codesandbox.io/s/gridjs-mre-formatter-with-server-forked-bzlirt?file=/src/App.js).

With react version 18 it works fine.
