### ISSUE TITLE
[ERROR]: The container element [object HTMLDivElement] is not empty.

### ISSUE THREAD

**Issue by LB26121** [grid-js/gridjs-react#408]
No matter if I use the gridjs react variant or include it differently, the error 
`[ERROR]: The container element [object HTMLDivElement] is not empty. Make sure the container is empty and call render() again`
always appears.

Also the options with force render and update have made no change.

The error has no consequences.

![Bildschirmfoto 2022-10-04 um 16 54 11](https://user-images.githubusercontent.com/87040521/193852829-b8d18bac-aef5-424c-99d8-8637dc0b192e.png)

**Short code snippet how I use it**
`data=[{ id='123' }, { id='456' },...]`
`<Grid data={data} columns={[{ name: 'ID' },...]} sort="true" className={{ sort: 'btn--sort' }} />`

In the columns object I use the `formater` and `_` to display some additional HTML in one column.
`{name: 'Status', formatter: (cell, row) =>
	_(
		<div className="container--flex-left">
			<div className={'has-status ${getStatusColor(cell)}'}>
				<i className={'icon icon-${getStatusIcon(cell)}'} />
			</div>
...
		</div>
	),
},`

![Bildschirmfoto 2022-10-04 um 16 47 57](https://user-images.githubusercontent.com/87040521/193852356-200db626-f773-4eff-8769-0f6cffb20be3.png)

**Versions**
react: 18.2.0
gridjs: 5.1.0
gridjs-react: 5.1.0

**Comment by Mspagnolo27248** [comment]
I have the same issue

**Comment by augiwan** [comment]
+1

**Comment by davidhagg** [comment]
+1

**Comment by Soujiro17** [comment]
+1

**Comment by Juanperezc** [comment]
+1

**Comment by MehdiBenbahri** [comment]
+1

**Comment by ikkhar** [comment]
+1

**Comment by craive** [comment]
Upgraded to versions:

gridjs: 6.0.6
gridjs-react: 6.0.1

...and this issues still persists.
