### ISSUE TITLE
resizable is not working in 5.1.0 verison

### ISSUE THREAD

**Issue by houssem1-2020** [grid-js/gridjs-react#409]
using react 18 and above you can't use last versions of gridjs and gridjs-react , because of reactDom issue (ReactDOM.render is no longer supported in React 18. Use createRoot instead) , in older vesion of grid js resizable is working well , but in last version (5.1.0) it just show to resizing arrow without any resizing achived !

**Comment by Xoouu** [comment]
Yep, this should definitely be fixed.
