### ISSUE TITLE
Error - ReactDOM.render is no longer supported in React 18, when using _

### ISSUE THREAD

**Issue by punit1108** [grid-js/gridjs-react#417]
**Describe the bug**
When i try to create a custom Component in react using the `_` function, the following error appears - 

`
app-index.js:31  Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
`

**To Reproduce**
1. Add a custom component like so - 
```
const columns = [{
  name: 'Status',
  id: 'status',
  formatter: (cell: any) => _(<StatusBadge status={cell} />)
}, {
  name: 'Frequency',
  id: 'recurring'
}]
```

**Expected behavior**
The library should be compatible with React 18

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser chrome, edge
 - Version 118

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UmarMansyur** [comment]
i also get the same error.

**Comment by UmarMansyur** [comment]
![Uploading Screenshot 2023-11-26 065415.png…]()

**Comment by afshinm** [comment]
Fixed.
