### ISSUE TITLE
Keep pagination page number and sorting order after setData

### ISSUE THREAD

**Issue by qaa1** [grid-js/gridjs-react#74]
I'd like to keep the pagination page number and sorting order after setData.

You can reproduce resetting the page and sorting here:
https://codesandbox.io/s/gridjs-react-update-state-forked-qot36?file=/src/App.js

I guess it's not only removing row but also changing status inside the table because it also needs to call setData or something like that.

**Comment by afshinm** [comment]
hey @qaa1 

Yes, the current version resets the internal state after `forceRender()` and that resets the page number: https://github.com/grid-js/gridjs-react/blob/master/src/grid.tsx#L25

It's not a `gridjs-react` bug and should be fixed in the main gridjs library. I will open a ticket.
